
# ========= Usuarios =========
# Criar usuário 
POST http://localhost:3000/users
Content-Type: application/json

{
  "nome": "Rick Sanchez",
  "email": "rick@email.com",
  "senha": "123456"
}
###
# Listar users
GET http://localhost:3000/users
Content-Type: application/json

###

# Listar user específico

GET http://localhost:3000/users/453b28dd-abe9-4aaa-adbc-cfbbe786d6ac


###

# Atualizar usuário 

PUT http://localhost:3000/users/1c587cce-567e-4612-bbfe-d5ea0070e17a
Content-Type: application/json

{
  "nome": "Pedro Siqueira",
  "email": "pedrolindo@email.com",
  "senha": "123456"
}

### 

# Deletar usuário
DELETE http://localhost:3000/users/c077cb6e-56da-4f32-a251-547afc113054
Content-Type: application/json


### Login do usuário
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "admin@teste.com",
  "senha": "123456"
}

### ==== CARROS ====

### Listar todos os carros
GET http://localhost:3000/carros
Content-Type: application/json

### Criar novo carro
POST http://localhost:3000/carros
Content-Type: application/json

{
  "modelo": "Carro teste",
  "potencia": 320,
  "ano_fabricacao": 2019,
  "marca_id": "e1fd5906-53bc-451a-be39-5c546de87c74",
  "user_id": "f83184ba-6e53-4aa5-9d05-491bb64188a6"
}

### Atualizar carro
PUT http://localhost:3000/carros/34b80dc9-47c2-47c5-a271-40c4cd568b8d
Content-Type: application/json

{
  "modelo": "Supra MK5",
  "potencia": 340,
  "ano_fabricacao": 2024,
  "marca_id": "593877e1-507b-48d4-8c98-c5841ad831d7",
  "user_id": "86995fee-8799-4fe7-ae2e-475df12d0f72"
}

### Deletar carro
DELETE http://localhost:3000/carros/9e788ee8-fe01-4d6a-aa60-784b16755efb
Content-Type: application/json

### ==== MARCAS ====

### Listar todas as marcas
GET http://localhost:3000/marcas
Content-Type: application/json
